# This file was *autogenerated* from the file one_way_accumulator.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_0xFF = Integer(0xFF)#!/usr/bin/env sage

import hashlib
import time

###########################################################
#
# Utility functions
#
###########################################################

def string2int(msg):
    # Warning: Trailing zeros ('\x00') are omitted!
    assert(msg[-_sage_const_1 ] != '\x00')
    msg = list(reversed(map(ord, list(msg))))
    m = msg[_sage_const_0 ]
    for c in msg[_sage_const_1 :]:
        m = (m << _sage_const_8 ) + c
    return(m)

def int2string(i):
    msg = []
    while(i > _sage_const_0 ):
        msg += [chr(int(i) & _sage_const_0xFF )]
        i = i >> _sage_const_8 
    return("".join(msg))


###########################################################
#
# One-way accumulator
#
###########################################################

n = 561508665948087545352987253256813938921L
referenceAccumulator = 230757756511379468965215489779427891997L

personalAccumulators = \
    [ ('Alice', 130436513274301151185661691739554173861L)
    , ('Bob', 266499640847330629410299179439453563206L)
    , ('Carol', 418929332127962703995790743851931669742L)
    , ('Eve', 479892121746869991037495826724031834611L)
    ]

def h(x, y, n):
    return pow(x, y, n)

# You suspect that one of the persons who claim to be members
# of the cabal is a snitch. In order to identify
# the snitch, you have to check their credentials.

def checkMembership(referenceAccumulator,
                    personalAccumulator,
                    person,
                    n):
    return referenceAccumulator == h(personalAccumulator, string2int(person), n)

# Now you know who is the snitch. Your next task is to provide
# fake credentials for the snitch. Calculate a personal accumulator
# for the snitch that passes the membership test!

def fakeCredentials(referenceAccumulator,
                    person,
                    n):
    return pow(referenceAccumulator, _sage_const_1 /string2int(person))

def findTheSnitch():
    for (person, acc) in personalAccumulators:
        if(not(checkMembership(referenceAccumulator=referenceAccumulator,
                               personalAccumulator=acc,
                               person=person,
                               n=n))):
            return(person)

if __name__ == "__main__":
    # Find the snitch
    snitch = findTheSnitch()
    assert(hashlib.sha256(snitch).hexdigest() ==
           'b9bae658d96579857efe22dee62673a31355446ddc6ad270ec046aa8c717081c')
    # Provide fake credentials for snitch
    fakeAccumulator = fakeCredentials(referenceAccumulator=referenceAccumulator,
                                      person=snitch,
                                      n=n)
    assert(checkMembership(referenceAccumulator=referenceAccumulator,
                          personalAccumulator=fakeAccumulator,
                          person=snitch,
                          n=n))
